apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nuxpert
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nuxpert
    spec:
      containers:
        - name: nuxpert
          image: gcr.io/kubernetes-221921/nuxpert:latest
          ports:
            - containerPort: 5000

# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: node-app-service
# spec:
#   selector:
#     app: node-app
#   ports:
#     - protocol: "TCP"
#       port: 8080
#       targetPort: 8080
#       nodePort: 30000
#   type: LoadBalancer

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "nuxpert-service"
  namespace: "default"
  labels:
    app: "nuxpert"
spec:
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  selector:
    app: "nuxpert"
  type: "ClusterIP"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nuxpert-microservice
spec:
  hosts:
  - "*"
  gateways:
  - http-gateway
  http:
  - route:
    - destination:
        port:
          number: 5000
        host: nuxpert-service
